dist: trusty
language: tex
sudo: false

branches:
  except:
    /^v[0-9]+\.[0-9]+\.[0-9]+/

install:
  - cp -n texlive* /tmp/
  - source /tmp/texlive_install.sh
  - tlmgr install multicol calc ifthen geometry amsmath amsthm amfonts amssymb color graphicx overpic
  - tlmgr install hyperref listings

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_script:
  - source .version

script:
  - pdflatex -interaction=nonstopmode -halt-on-error Cheat_Sheet.tex
  - pdflatex -interaction=nonstopmode -halt-on-error "\providecommand{\docversion}{${VERSION}.${TRAVIS_BUILD_NUMBER}} \input{Cheat_Sheet.tex}"

deploy:
  - provider: releases
    api_key: $GIT_AUTH
    skip_cleanup: true
    prerelease: true
    file: "Cheat_Sheet.pdf"
    tag_name: "v${VERSION}.${TRAVIS_BUILD_NUMBER}"
    name: "v${VERSION}.${TRAVIS_BUILD_NUMBER}"
    on:
      tags: false
      branch: "master"
  - provider: releases
    api_key: $GIT_AUTH
    skip_cleanup: true
    file:
      - "Cheat_Sheet.pdf"
    on:
      tags: true